language: node_js
node_js:
  - 12.18.4
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: l1QqB6TI404LaszzNPQm+aXFS+4jrT2VSEOgO1fcqMkehAoI1GtRmZZazHWa9ukC92SBLXNc7n4pw+xDKjC2XSbv5t+aX5JlZCilzrp980HiEATrskCNL7oAlQ9wVnYtoqgijapm67GZQixJ72bHJnMHvdpBKZ9aa3+l3IcDNBOWXx7kxEnIA8dp5N5KRR3tcjAzK4zr4mxUo79EY8Fjc35VDGaUxbJ9zaMXNv1CA4v6kaPVsZn+ORHzh+yWpu56A3o/bBFmRvlzaAG2ElEG/XdCdbed9f5jJnlCMZIe4dJcXVfEkEo5dES7nmIGWhtX5+b5ODMFvQPAiVD4FgDo4Hrb0KjFGsMzwo3dls4MCr3pQu8qdv63+fGJ57gStNL6wYO3VZ4IE2Iu0TMV1KbNWlS1RKTQ/7UztKcV/6alHNRMbFhLqoG+EJUx+KSJr3TcwiHJjINMxFtf5g+GqRU2m8II5hcyZQCaDGHwqKwRQsbEXX7+V7RLplVvBOGat2UnIt+p4QLIe2MXj3GKn+t/7RZlp7mtoyBczUvDPzJXimm+8klT9kjYcn5zkQyDWL375H/IXd7BGNuM703tp5QvMZg0nVvHmueVGFhKa2fSIk9H4scD/lbJlbCfEpYptmFskXLh60lVugdNWQwvdpyf1WF0Y6maD4pMTSyMxEcEufE=
  app: black-box-12
