language: node_js
node_js:
  - 12.18.4
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: cFmbORfiV9zlUbaNIE1VRORhEQxSn1wddFp22vM0yzMhaxUU5EqzNSH6uus6SAf+CbXwQ8tVbv9q4lLONj27wgxBWEWDXfl6jTKvWjTHj+5PCu2cjl2HWXhqgqM25ZSQlTRy1ANs9pAl5QLCvzA+BjLZwymzoJiJujpG8ZwMcYkfwVpfpRa+UJOrcKQbtnFNnZb10jWkzD9SxG+oC6H3eMMNPJjJiMXrSKUU+MGAdC9oFfctFqMr4vcWnz42554Y1f0TDyjG5uMyVRxCycTQRU/uIb2lF/H3qUPsK3Tq1xt1x55JWgJTlj9AijiTLf5L7EaIxzjIs4Cz2xSEKvnZoFHAZVX7eopvt3UtsRegMLKsB961Tv9Yw/xjeSAPiwbfGQlXxKljqtWCz38f+Z4bYy6bXiSsS/mU3HiuGMsCR59BMCkSXjpUTRDWZrqhSzpGYMWrj9CtIIKv6kx3MdBISdw8e7eKH2OOkGQM0h8ihyFOONaaoxlQvUTxLsX6NS5kQzjgrI26PjB+ai1tNKUTyYqD3thOYAzYUNtOgmTBPe0oQALXeCWrTlHtjxgcCh1aI5BHK7iNPFeceA6gcIk9GC3vgQ9jP9a5Yhyfhw2QDAsNGaTj9C+fOYswYCuE7u3cj+UD5wlp4Hp/aF0DtOFV2Xxa/OJYYbsj5ZdiGm6vH20=
